### ISSUE TITLE
StegImage::put

### ISSUE THREAD

**Issue by MicahSchiewe** [nnazo/CSI3344-Steganography#4]
Write one byte's worth of data into the RGB low-order bits. May want some helper functions. Be careful not to overflow image dimensions.

General strategy:
```
for each bit 'b' in the character:
    let c2 = peeked next character
    Embed  b in c2
    put c2 into stream (will overwrite original)
```

**Comment by nnazo** [comment]
It's been a little while so I might not remember everything we discussed about this, but does this method really need to worry about overflowing image dimensions? Doesn't the `verifyMessageFits(message)` method take care of that?
